# Generated by Django 5.0.2 on 2024-02-27 21:59

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Contact",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("company", models.CharField(blank=True, max_length=100)),
                ("phone_number", models.CharField(blank=True, max_length=20)),
                ("email", models.EmailField(max_length=254)),
                ("message", models.TextField()),
                (
                    "topic",
                    models.CharField(
                        choices=[
                            ("enquiry", "Enquiry"),
                            ("sales", "Sales"),
                            ("support", "Support"),
                        ],
                        max_length=20,
                    ),
                ),
            ],
        ),
    ]
